name: Keep Repl Alive

# 매 5분마다 자동 실행
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  wake_repl:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit Keep-Alive URL
        run: |
          curl -m 10 https://32605038-036c-4f02-b48b-496cd74e0ba2-00-2hz4yb0kyc88v.pike.replit.dev/ || true
